const Order = require('../models/Order');
const Notification = require('../models/Notification');
const Product = require('../models/Product');
const Coupon = require('../models/Coupon'); // ✅ Add Coupon import
const { broadcastNotification, broadcastUnreadCount } = require('../routes/notificationSSE');

// @desc    Create new order
// @route   POST /api/order
// @access  Public
exports.createOrder = async (req, res) => {
  try {
    const {
      userId,
      cartItems,
      addressInfo,
      paymentMethod,
      shippingCharge,
      shippingType,
      totalAmount,
      couponCode,
      discountAmount
    } = req.body;

    console.log("📦 Creating order:", { userId, itemCount: cartItems?.length, couponCode });

    // Validation
    if (!cartItems || cartItems.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'Cart is empty'
      });
    }

    if (!addressInfo || !addressInfo.name || !addressInfo.phone || !addressInfo.address) {
      return res.status(400).json({
        success: false,
        message: 'Address information is incomplete'
      });
    }

    // Validate stock for each item
    for (const item of cartItems) {
      const product = await Product.findById(item.productId);
      
      if (!product) {
        return res.status(404).json({
          success: false,
          message: `Product ${item.title} not found`
        });
      }

      let availableStock = 0;
      
      // Check stock based on product type
      if (product.hasSizeVariants && product.sizeVariants && product.sizeVariants.length > 0) {
        const sizeOption = product.sizeVariants.find(s => s.size === item.size);
        if (!sizeOption) {
          return res.status(400).json({
            success: false,
            message: `Size ${item.size} not available for ${item.title}`
          });
        }
        availableStock = sizeOption.stock || 0;
      } else {
        // Single size product or no size variants
        availableStock = product.stock || 0;
      }

      if (availableStock < item.quantity) {
        return res.status(400).json({
          success: false,
          message: `Insufficient stock for ${item.title}. Only ${availableStock} available`
        });
      }
    }

    // ✅ Validate coupon if provided (double-check on backend)
    let validatedCoupon = null;
    if (couponCode) {
      try {
        // Calculate subtotal using effective prices (salePrice if available, otherwise regular price)
        const subtotal = cartItems.reduce((sum, item) => {
          const effectivePrice = item.salePrice || item.price;
          return sum + (effectivePrice * item.quantity);
        }, 0);
        
        validatedCoupon = await Coupon.validateCoupon(
          couponCode,
          subtotal,
          userId,
          cartItems
        );
        console.log("✅ Coupon validated:", validatedCoupon.couponCode);
      } catch (couponError) {
        console.warn("⚠️ Coupon validation failed:", couponError.message);
        // Return error for strict validation
        return res.status(400).json({
          success: false,
          message: couponError.message || 'Invalid coupon code'
        });
      }
    }

    // Transform cartItems to match Order schema
    const transformedCartItems = cartItems.map(item => ({
      product: item.productId, // This is the reference to Product model
      productId: item.productId,
      title: item.title,
      image: item.image,
      price: item.price,
      quantity: item.quantity,
      size: item.size,
      color: item.color || ''
    }));

    console.log("🔄 Creating order with transformed items...");

    // Create order - orderNumber will be auto-generated by pre-save hook
    const order = new Order({
      userId: userId || null,
      cartItems: transformedCartItems,
      addressInfo,
      paymentMethod: paymentMethod || 'COD',
      shippingCharge: shippingCharge || 0,
      shippingType: shippingType || 'inside',
      totalAmount,
      couponCode: couponCode || null,
      discountAmount: discountAmount || 0,
      orderStatus: 'pending',
      paymentStatus: 'pending'
    });

    // Save order (this triggers the pre-save hook to generate orderNumber)
    await order.save();
    
    console.log("✅ Order saved with number:", order.orderNumber);

    // ✅ Increment coupon usage if coupon was used
    if (validatedCoupon) {
      try {
        await validatedCoupon.incrementUsage();
        console.log("✅ Coupon usage incremented:", validatedCoupon.couponCode, "- Used:", validatedCoupon.usedCount);
      } catch (couponUpdateError) {
        console.error("❌ Failed to increment coupon usage:", couponUpdateError.message);
        // Don't fail the order if coupon update fails
      }
    }

    // Update product stock
    for (const item of cartItems) {
      const product = await Product.findById(item.productId);
      
      if (!product) continue; // Skip if product not found
      
      if (product.hasSizeVariants && product.sizeVariants && product.sizeVariants.length > 0) {
        const sizeIndex = product.sizeVariants.findIndex(s => s.size === item.size);
        if (sizeIndex !== -1) {
          product.sizeVariants[sizeIndex].stock = Math.max(0, product.sizeVariants[sizeIndex].stock - item.quantity);
        }
      } else {
        product.stock = Math.max(0, product.stock - item.quantity);
      }
      
      await product.save();
    }

    // Create notification (wrap in try-catch to not fail order if notification fails)
    try {
      const notification = await Notification.createOrderNotification(order);
      
      // Broadcast notification via SSE to all connected admins
      if (typeof broadcastNotification === 'function') {
        broadcastNotification(notification);
      }
      if (typeof broadcastUnreadCount === 'function') {
        broadcastUnreadCount();
      }
    } catch (notifError) {
      console.warn('⚠️ Notification creation failed:', notifError.message);
      // Continue anyway - order is created successfully
    }

    console.log("✅ Order created:", order.orderNumber);

    res.status(201).json({
      success: true,
      message: 'Order placed successfully',
      order
    });
  } catch (error) {
    console.error('💥 Create order error:', error);
    console.error('Error details:', error.message);
    console.error('Error stack:', error.stack);
    
    res.status(500).json({
      success: false,
      message: 'Failed to create order',
      error: error.message,
      details: process.env.NODE_ENV === 'development' ? error.stack : undefined
    });
  }
};

// @desc    Get all orders (Admin)
// @route   GET /api/order/admin/all
// @access  Private/Admin
exports.getAllOrders = async (req, res) => {
  try {
    const { status, page = 1, limit = 20, search } = req.query;

    const query = {};
    if (status && status !== 'all') {
      query.orderStatus = status;
    }
    if (search) {
      query.$or = [
        { orderNumber: { $regex: search, $options: 'i' } },
        { 'addressInfo.name': { $regex: search, $options: 'i' } },
        { 'addressInfo.phone': { $regex: search, $options: 'i' } }
      ];
    }

    const skip = (parseInt(page) - 1) * parseInt(limit);

    const orders = await Order.find(query)
      .populate('userId', 'name email')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    const total = await Order.countDocuments(query);

    res.json({
      success: true,
      orders,
      pagination: {
        total,
        page: parseInt(page),
        pages: Math.ceil(total / parseInt(limit))
      }
    });
  } catch (error) {
    console.error('Get all orders error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch orders',
      error: error.message
    });
  }
};

// @desc    Get user orders
// @route   GET /api/order/user/:userId
// @access  Private
exports.getUserOrders = async (req, res) => {
  try {
    const { userId } = req.params;
    const { page = 1, limit = 10 } = req.query;

    const skip = (parseInt(page) - 1) * parseInt(limit);

    const orders = await Order.find({ userId })
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    const total = await Order.countDocuments({ userId });

    res.json({
      success: true,
      orders,
      pagination: {
        total,
        page: parseInt(page),
        pages: Math.ceil(total / parseInt(limit))
      }
    });
  } catch (error) {
    console.error('Get user orders error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch orders',
      error: error.message
    });
  }
};

// @desc    Get order by ID
// @route   GET /api/order/:id
// @access  Private
exports.getOrderById = async (req, res) => {
  try {
    const { id } = req.params;

    const order = await Order.findById(id)
      .populate('userId', 'name email phone')
      .populate('cartItems.product');

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    res.json({
      success: true,
      order
    });
  } catch (error) {
    console.error('Get order error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch order',
      error: error.message
    });
  }
};

// @desc    Update order status (Admin)
// @route   PUT /api/order/:id/status
// @access  Private/Admin
exports.updateOrderStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status, note, trackingNumber, courierService } = req.body;

    const order = await Order.findById(id);
    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    // Update status with history
    await order.updateStatus(status, note, req.user?._id);

    // Update tracking info if provided
    if (trackingNumber) order.trackingNumber = trackingNumber;
    if (courierService) order.courierService = courierService;

    await order.save();

    // Create notification for status change
    try {
      const notification = await Notification.create({
        type: 'order',
        title: 'Order Status Updated',
        message: `Order ${order.orderNumber} status changed to ${status}`,
        orderId: order._id,
        orderNumber: order.orderNumber,
        userId: order.userId,
        priority: 'medium'
      });

      // Broadcast notification via SSE
      if (typeof broadcastNotification === 'function') {
        broadcastNotification(notification);
      }
      if (typeof broadcastUnreadCount === 'function') {
        broadcastUnreadCount();
      }
    } catch (notifError) {
      console.warn('⚠️ Notification creation failed:', notifError.message);
    }

    res.json({
      success: true,
      message: 'Order status updated',
      order
    });
  } catch (error) {
    console.error('Update order status error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to update order status',
      error: error.message
    });
  }
};

// @desc    Update order admin notes
// @route   PUT /api/order/:id/notes
// @access  Private/Admin
exports.updateOrderNotes = async (req, res) => {
  try {
    const { id } = req.params;
    const { adminNotes } = req.body;

    const order = await Order.findByIdAndUpdate(
      id,
      { adminNotes },
      { new: true }
    );

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    res.json({
      success: true,
      message: 'Admin notes updated',
      order
    });
  } catch (error) {
    console.error('Update order notes error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to update notes',
      error: error.message
    });
  }
};

// @desc    Delete order (Admin)
// @route   DELETE /api/order/:id
// @access  Private/Admin
exports.deleteOrder = async (req, res) => {
  try {
    const { id } = req.params;

    const order = await Order.findByIdAndDelete(id);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found'
      });
    }

    res.json({
      success: true,
      message: 'Order deleted successfully'
    });
  } catch (error) {
    console.error('Delete order error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to delete order',
      error: error.message
    });
  }
};

// @desc    Get order statistics (Admin)
// @route   GET /api/order/admin/stats
// @access  Private/Admin
exports.getOrderStats = async (req, res) => {
  try {
    const totalOrders = await Order.countDocuments();
    const pendingOrders = await Order.countDocuments({ orderStatus: 'pending' });
    const confirmedOrders = await Order.countDocuments({ orderStatus: 'confirmed' });
    const processingOrders = await Order.countDocuments({ orderStatus: 'processing' });
    const shippedOrders = await Order.countDocuments({ orderStatus: 'shipped' });
    const deliveredOrders = await Order.countDocuments({ orderStatus: 'delivered' });
    const cancelledOrders = await Order.countDocuments({ orderStatus: 'cancelled' });

    const totalRevenue = await Order.aggregate([
      { $match: { orderStatus: { $ne: 'cancelled' } } },
      { $group: { _id: null, total: { $sum: '$totalAmount' } } }
    ]);

    res.json({
      success: true,
      stats: {
        totalOrders,
        pendingOrders,
        confirmedOrders,
        processingOrders,
        shippedOrders,
        deliveredOrders,
        cancelledOrders,
        totalRevenue: totalRevenue[0]?.total || 0
      }
    });
  } catch (error) {
    console.error('Get order stats error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch statistics',
      error: error.message
    });
  }
};